# Generated by Django 5.2.13 on 2026-04-23 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='duraion',
            new_name='duration',
        ),
    ]
