# Generated by Django 5.2.13 on 2026-04-27 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_rename_duraion_movie_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='show',
        ),
    ]
