# Generated by Django 5.2.13 on 2026-05-01 11:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_remove_booking_show'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='show',
            name='screen',
        ),
        migrations.AddField(
            model_name='show',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='show',
            name='movie_name',
            field=models.CharField(default='Default Movie', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='show',
            name='show_time',
            field=models.TimeField(),
        ),
    ]
