# Generated by Django 5.2.13 on 2026-05-14 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_remove_movie_genre_remove_movie_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='price',
            field=models.IntegerField(default=150),
        ),
    ]
