# Generated by Django 5.2.13 on 2026-05-15 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_seat_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(default='Online', max_length=50),
        ),
    ]
