# Generated by Django 5.2.13 on 2026-05-20 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_movie_vote_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
