# Generated by Django 5.2.13 on 2026-05-20 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_movie_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seat',
            name='lock_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seat',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seat',
            name='locked_by',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
