# Generated by Django 5.2.13 on 2026-05-21 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_seat_is_locked_seat_lock_expires_at_seat_locked_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='budget_level',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
