# Generated by Django 5.2.13 on 2026-05-22 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_booking_user_alter_booking_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='budget_level',
            field=models.CharField(default='medium', max_length=20),
        ),
    ]
