# Generated by Django 5.2.13 on 2026-05-26 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0017_continuewatching'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComboOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('offer_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
    ]
