# Generated by Django 5.2.13 on 2026-05-27 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0020_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_ticket_used',
            field=models.BooleanField(default=False),
        ),
    ]
