# Generated by Django 5.2.13 on 2026-06-04 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0023_event_slug_alter_event_date_alter_event_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='language',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
